/**
 * Fixtures pour les tests unitaires — lignes brutes telles qu'elles
 * sortiraient d'un batchGet Google Sheets (tableaux 2D, en-têtes exactement
 * comme spécifiées dans la structure de données, accents compris).
 *
 * Couvre explicitement : accents dans les en-têtes, booléens sous
 * plusieurs formes (TRUE/VRAI/vrai/1/oui/x/vide), cellules vides, colonnes
 * AA/AB absentes OU présentes-mais-vides, deux joueurs portant le même
 * numéro dans deux équipes différentes, une donnée fictive à exclure, une
 * photo refusée (consentement manquant) et une URL de photo non HTTPS.
 *
 * Suffixe .test-data.ts (et non .test.ts) : ce fichier n'a aucun test lui-
 * même, seulement des données — Vitest ne doit pas essayer de l'exécuter
 * comme une suite.
 */

export const ENTETES_EQUIPES = [
  "id_equipe",
  "saison",
  "sport",
  "équipe",
  "catégorie",
  "genre",
  "division",
  "statut_équipe",
  "nb_joueurs",
  "nb_entraîneurs",
  "ouvrir_équipe",
  "google_calendar_id",
  "source_horaires",
  "synchronisation",
  "fuseau_horaire",
  "slug_site",
  "notes",
];

export const LIGNES_EQUIPES: unknown[][] = [
  [
    "eq-basket-cadet-m",
    "2026-2027",
    "basketball",
    "Cadet Masculin",
    "Cadet",
    "Masculin",
    "RSEQ Québec",
    "Actif",
    "12",
    "2",
    "TRUE",
    "cal-cadet-m@group.calendar.google.com",
    "google_calendar",
    "VRAI",
    "America/Toronto",
    "cadet-masculin",
    "",
  ],
  [
    "eq-basket-juvenile-m",
    "2026-2027",
    "basketball",
    "Juvénile Masculin",
    "Juvénile",
    "Masculin",
    "RSEQ Québec",
    "Actif",
    "12",
    "2",
    "1",
    "",
    "a-confirmer",
    "",
    "America/Toronto",
    "juvenile-masculin",
    "",
  ],
  // Équipe sans aucune ligne MEMBRES correspondante — doit produire une réponse "vide", pas une erreur.
  [
    "eq-soccer-cadet-m",
    "2026-2027",
    "soccer",
    "Cadet Masculin",
    "Cadet",
    "Masculin",
    "",
    "Actif",
    "0",
    "0",
    "FALSE",
    "",
    "",
    "",
    "America/Toronto",
    "cadet-masculin",
    "Pas encore d'effectif saisi",
  ],
];

export const ENTETES_MEMBRES_AVEC_AA_AB = [
  "id_membre",
  "id_personne",
  "id_equipe",
  "rôle",
  "prénom",
  "nom",
  "nom_complet",
  "courriel_privé",
  "numéro",
  "poste",
  "capitaine",
  "niveau_scolaire",
  "statut_membre",
  "statut_compte",
  "auth_user_id",
  "photo_url",
  "photo_storage_path",
  "statut_photo",
  "consentement_photo",
  "date_consentement",
  "donnée_fictive",
  "accès_chat",
  "saison",
  "date_ajout",
  "date_départ",
  "notes",
  "publication_profil",
  "publication_photo",
];

/** Même en-têtes, mais SANS les colonnes AA/AB — l'admin ne les a pas encore ajoutées. */
export const ENTETES_MEMBRES_SANS_AA_AB = ENTETES_MEMBRES_AVEC_AA_AB.slice(0, 26);

export const LIGNES_MEMBRES: unknown[][] = [
  // Joueur publiable, numéro 25, équipe Cadet Masculin — photo publique conforme.
  [
    "mb-001",
    "pers-001",
    "eq-basket-cadet-m",
    "Joueur",
    "Alice",
    "Tremblay",
    "",
    "alice.parent@exemple.com",
    "25",
    "Meneuse",
    "VRAI",
    "Secondaire 3",
    "Actif",
    "actif",
    "",
    "https://lh3.googleusercontent.com/photo-alice.jpg",
    "drive/photos/alice.jpg",
    "approuvee",
    "Accordé",
    "2026-08-01",
    "FALSE",
    "TRUE",
    "2026-2027",
    "2026-08-01",
    "",
    "",
    "TRUE",
    "TRUE",
  ],
  // Même numéro 25, mais équipe DIFFÉRENTE (Juvénile Masculin) — doit cohabiter sans collision.
  [
    "mb-002",
    "pers-002",
    "eq-basket-juvenile-m",
    "Joueur",
    "Marc-Olivier",
    "Bouchard",
    "",
    "mo.bouchard@exemple.com",
    "25",
    "Ailier",
    "FALSE",
    "Secondaire 5",
    "Actif",
    "actif",
    "",
    "",
    "",
    "",
    "",
    "",
    "FALSE",
    "FALSE",
    "2026-2027",
    "2026-08-01",
    "",
    "",
    "TRUE",
    "FALSE",
  ],
  // Entraîneur publiable, sans numéro — categorieRole doit être "entraineur".
  [
    "mb-003",
    "pers-003",
    "eq-basket-cadet-m",
    "Entraîneur-chef",
    "Julie",
    "Gagnon",
    "",
    "julie.gagnon@exemple.com",
    "",
    "",
    "FALSE",
    "",
    "Actif",
    "actif",
    "",
    "",
    "",
    "",
    "",
    "",
    "FALSE",
    "FALSE",
    "2026-2027",
    "2026-08-01",
    "",
    "",
    "TRUE",
    "FALSE",
  ],
  // donnée_fictive = TRUE → jamais public, même si publication_profil = TRUE.
  [
    "mb-004",
    "pers-004",
    "eq-basket-cadet-m",
    "Joueur",
    "Prénom",
    "Fictif",
    "",
    "",
    "99",
    "Pivot",
    "FALSE",
    "",
    "Actif",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "TRUE",
    "",
    "2026-2027",
    "",
    "",
    "Exemple fictif du gabarit",
    "TRUE",
    "TRUE",
  ],
  // statut_membre = Inactif → jamais public.
  [
    "mb-005",
    "pers-005",
    "eq-basket-cadet-m",
    "Joueur",
    "Ancien",
    "Joueur",
    "",
    "",
    "7",
    "Ailier",
    "FALSE",
    "",
    "Inactif",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "FALSE",
    "",
    "2026-2027",
    "",
    "2026-09-15",
    "",
    "TRUE",
    "TRUE",
  ],
  // publication_profil = FALSE → jamais public malgré des données réelles valides.
  [
    "mb-006",
    "pers-006",
    "eq-basket-cadet-m",
    "Joueur",
    "Non",
    "Publié",
    "",
    "",
    "11",
    "Pivot",
    "FALSE",
    "",
    "Actif",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "FALSE",
    "",
    "2026-2027",
    "",
    "",
    "",
    "FALSE",
    "FALSE",
  ],
  // Profil public MAIS photo refusée : consentement manquant → photoUrl doit rester null.
  [
    "mb-007",
    "pers-007",
    "eq-basket-cadet-m",
    "Joueur",
    "Sans",
    "Consentement",
    "",
    "",
    "14",
    "Ailier",
    "FALSE",
    "",
    "Actif",
    "",
    "",
    "https://lh3.googleusercontent.com/photo-sans-consentement.jpg",
    "",
    "",
    "",
    "",
    "FALSE",
    "",
    "2026-2027",
    "",
    "",
    "",
    "TRUE",
    "TRUE",
  ],
  // Profil public, publication_photo = TRUE et consentement Accordé, mais URL non HTTPS → photoUrl doit rester null.
  [
    "mb-008",
    "pers-008",
    "eq-basket-cadet-m",
    "Joueur",
    "Url",
    "NonSecurisee",
    "",
    "",
    "21",
    "Pivot",
    "FALSE",
    "",
    "Actif",
    "",
    "",
    "http://exemple-non-securise.com/photo.jpg",
    "",
    "",
    "Accordé",
    "2026-08-01",
    "FALSE",
    "",
    "2026-2027",
    "",
    "",
    "",
    "TRUE",
    "TRUE",
  ],
  // nom_complet utilisé en repli car prénom/nom sont vides.
  [
    "mb-009",
    "pers-009",
    "eq-basket-cadet-m",
    "Joueur",
    "",
    "",
    "Nom Complet Seulement",
    "",
    "4",
    "Ailier",
    "FALSE",
    "",
    "Actif",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "FALSE",
    "",
    "2026-2027",
    "",
    "",
    "",
    "TRUE",
    "FALSE",
  ],
];
